services:
  metriclens:
    image: metriclens:dev
    build:
      context: .
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      metriclens_SCRAPE_INTERVAL: 5s
      metriclens_RETENTION: 15m
